public with sharing class ApplicationConstants {
    public static Boolean bypassIMSharingRulesTriggerLogic = false;
    public static Boolean bypassIMCreateVendorTriggerLogic = false;
    public static Boolean bypassReportingPeriodApprovalLogic = false;
    public static Boolean bypassOrgUnitIndicatorAfterDelete = false;   
    public static Boolean bypassOrgUnitIndicatorUpsertShare = false;
    public static Boolean bypassIndicatorResultsAfterUpdate = false;
    
    public static Boolean bypassIndicatorResultsAfterDelete = false;
    public static Boolean bypassReportingPeriodBeforeUpsertQOwner = false;
    public static Boolean bypassOrganizationIndicatorBeforeUpsertQOwner = false;
    
    public static Boolean byPassGoalAfterUpdate = false;
    public static Boolean byPassGoalBeforeUpsertQowner = false;
    
    public static Boolean byPassLFGoalBeforeUpsertQOwner = false;
    public static Boolean byPassLFGoalAfterUpdate = false;
    
    public static Boolean byPassLFPurposeBeforeUpsertQOwner = false;
    public static Boolean byPassLFPurposeAfterUpdate = false;
    
    public static Boolean byPassOrgUnitBeforeUpsert = false;
    public static Boolean byPassOrgUnitAfterUpdateGoals = false;
    
    
    //public static Boolean bypassContactSharingRulesTriggerLogic = false;
}